version: '3.8'
services:
  web:
    image: ghcr.io/VOTRE_USERNAME/VOTRE_REPO:latest
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - app-logs:/app/logs
    network_mode: "host"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

volumes:
  app-logs:
    driver: local
  app-data:
    driver: local
