name: Docker Image CI/CD

on:
  workflow_dispatch: 
    inputs:
      repo_url:
        description: 'https://github.com/IUT-Beziers/sae501-502app-spc/tree/QUALV3/Serveur'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: IUT-Beziers/sae501-502app-spc
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        path: source-repo

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./source-repo  # Pointe vers le dépôt source
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
