name: Docker Image CI/CD

on:
  push:
    branches: [ "QUALV3" ]  # Le branch où vous faites vos modifications
  pull_request:
    branches: [ "QUALV3" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # Utilise le Dockerfile du dépôt actuel
        load: true  # Charge l'image localement pour tests
        tags: test-image:latest

    - name: Test Docker image
      run: |
        # Ajouter ici vos tests
        docker run --rm test-image:latest /bin/sh -c "python -m pytest" || exit 1

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/VOTRE_ORGANISATION/VOTRE_REPO_PUBLIC:latest
          ghcr.io/VOTRE_ORGANISATION/VOTRE_REPO_PUBLIC:${{ github.sha }}
